import React from 'react';
import { iBMPlexMono } from '@/utils/fonts';
import '@/styles/core/_global.scss';

import Providers from '@/lib/providers';
import Header from '@/Components/Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={iBMPlexMono.variable}>
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
